#coding:utf-8

import os, sys

UYU_OP_OK = 0
UYU_OP_ERR = -1

#订单状态
UYU_ORDER_STATUS_SUCC = 0
UYU_ORDER_STATUS_NEED_CONFIRM = 1
UYU_ORDER_STATUS_CANCEL = 2
#订单状态MAP
UYU_ORDER_STATUS_MAP = {
    UYU_ORDER_STATUS_SUCC: '成功',
    UYU_ORDER_STATUS_NEED_CONFIRM: '待确认',
    UYU_ORDER_STATUS_CANCEL: '撤销',
}

#基础用户角色
UYU_USER_ROLE_BASE     = 1
#渠道用户
UYU_USER_ROLE_CHAN     = 2
#门店用户
UYU_USER_ROLE_STORE    = 3
#医院用户
UYU_USER_ROLE_HOSPITAL = 4
#视光师用户
UYU_USER_ROLE_EYESIGHT = 5
#公司超级管理员
UYU_USER_ROLE_SUPER    = 6
#消费者
UYU_USER_ROLE_COMSUMER = 7
#系统角色
UYU_USER_ROLE_MAP = {
    UYU_USER_ROLE_BASE: '基础用户',
    UYU_USER_ROLE_CHAN: '渠道',
    UYU_USER_ROLE_STORE: '门店',
    UYU_USER_ROLE_HOSPITAL: '医院',
    UYU_USER_ROLE_EYESIGHT: '视光师',
    UYU_USER_ROLE_SUPER: '管理员',
    UYU_USER_ROLE_COMSUMER: '消费者',
}

#用户状态
#正常
UYU_USER_STATE_OK = 1
#封禁
UYU_USER_STATE_FORBIDDEN = 2
#注销
UYU_USER_STATE_CANCEL = 3
UYU_USER_STATE_MAP = {
    UYU_USER_STATE_OK: '正常',
    UYU_USER_STATE_FORBIDDEN: '封禁',
    UYU_USER_STATE_CANCEL: '注销'
}

#用户profile状态
#未审核
UYU_USER_PROFILE_STATE_UNAUDITED = 1
#已经审核
UYU_USER_PROFILE_STATE_AUDITED = 2


#渠道信息状态
#启用
UYU_CHAN_STATUS_OPEN = 0
#关闭
UYU_CHAN_STATUS_CLOSE = 1
UYU_CHAN_MAP = {
    UYU_CHAN_STATUS_OPEN : '启用',
    UYU_CHAN_STATUS_CLOSE : '关闭'
}

#门店状态
#启用
UYU_STORE_STATUS_OPEN = 0
#关闭
UYU_STROE_STATUS_CLOSE = 1
UYU_STORE_STATUS_MAP = {
    UYU_STORE_STATUS_OPEN : '启用',
    UYU_STROE_STATUS_CLOSE : '关闭'
}
#门店角色
#门店
UYU_STORE_ROLE_STORE = 0
#医院
UYU_STORE_ROLE_HOSPITAL = 1
#0 门店, 1 医院

UYU_STORE_ROLE_MAP = {
    UYU_STORE_ROLE_STORE: '门店',
    UYU_STORE_ROLE_HOSPITAL: '医院'
}

#视光师门店绑定状态
#已绑定
UYU_STORE_EYESIGHT_BIND = 0
#已删除
UYU_STORE_EYESIGHT_UNBIND = 1
UYU_STORE_EYESIGHT_BIND_MAP = {
    UYU_STORE_EYESIGHT_BIND : '已绑定',
    UYU_STORE_EYESIGHT_UNBIND : '已删除'
}

#设备状态
#正常
UYU_DEVICE_ENABLE = 0
UYU_DEVICE_DISABLE = 1

UYU_DEVICE_MAP = {
    UYU_DEVICE_ENABLE : '启用',
    UYU_DEVICE_DISABLE : '关闭',
}

#训练使用状态
#已使用
UYU_TRAIN_USE_USED = 0

UYU_TRAIN_USE_MAP = {
    UYU_TRAIN_USE_USED : '已使用',
}

#系统角色
UYU_SYS_ROLE_OP = 0
UYU_SYS_ROLE_CHAN = 1
UYU_SYS_ROLE_STORE = 2

#使用权限定义
PERMISSION_CHECK = {
    UYU_SYS_ROLE_OP: (UYU_USER_ROLE_SUPER, ),
    UYU_SYS_ROLE_CHAN: (UYU_USER_ROLE_CHAN, ),
    UYU_SYS_ROLE_STORE: (UYU_USER_ROLE_STORE, UYU_USER_ROLE_HOSPITAL, UYU_USER_ROLE_EYESIGHT),
}


#业务操作类型busicd
#公司送训练点数给渠道
BUSICD_ORG_ALLOT_TO_CHAN = "ORG_ALLOT_TO_CHAN"
#渠道向公司购买训练点数
BUSICD_CHAN_BUY_TRAING_TIMES = "CHAN_BUY"
#渠道分配训练点数给门店
BUSICD_CHAN_ALLOT_TO_STORE = "CHAN_ALLOT_TO_STORE"
#门店分配训练点数给消费者
BUSICD_CHAN_ALLOT_TO_COSUMER = "STORE_ALLOT_TO_COMSUMER"
#注册赠送
BUSICD_ORG_REGISTER_PRESENTATION = "REGISTER_PRESENTATION"
#运营平台赠送
BUSICD_ORG_PRESENTATION = "ORG_PRESENTATION"
UYU_BUSICD_MAP = {
    BUSICD_ORG_ALLOT_TO_CHAN: '公司送训练点数给渠道',
    BUSICD_CHAN_BUY_TRAING_TIMES: '渠道向公司购买训练点数',
    BUSICD_CHAN_ALLOT_TO_STORE: '渠道分配训练点数给门店',
    BUSICD_CHAN_ALLOT_TO_COSUMER: '门店分配训练点数给消费者',
    BUSICD_ORG_REGISTER_PRESENTATION: '注册赠送点数',
    BUSICD_ORG_PRESENTATION: '运营平台赠送点数',
}

#订单类型
#分配
UYU_ORDER_TYPE_ALLOT = 0
#购买
UYU_ORDER_TYPE_BUY = 1
#赠送
UYU_ORDER_TYPE_PRESENTATION = 2

UYU_ORDER_TYPE_MAP = {
    UYU_ORDER_TYPE_BUY: '购买',
    UYU_ORDER_TYPE_ALLOT: '分配',
    UYU_ORDER_TYPE_PRESENTATION: '赠送'
}

#操作类别
#训练
UYU_OP_CATEGORY_TRAIN = 0
UYU_OP_CATEGORY_MAP = {
    UYU_OP_CATEGORY_TRAIN:  '训练'
}
#订单支付方式
#支付宝
UYU_ORDER_PAY_TYPE_ALIPAY  = 0
#微信
UYU_ORDER_PAY_TYPE_WCHART  = 1
#线下
UYU_ORDER_PAY_TYPE_OFFLINE = 2

UYU_ORDER_PAY_TYPE_MAP = {
    UYU_ORDER_PAY_TYPE_ALIPAY: '支付宝',
    UYU_ORDER_PAY_TYPE_WCHART: '微信',
    UYU_ORDER_PAY_TYPE_OFFLINE: '支付宝'
}


#渠道分成类型
#分成
UYU_CHAN_DIV_TYPE = 1
#次卡
UYU_CHAN_PREPAY_TYPE = 0

#门店分成类型
#分成
UYU_STORE_DIV_TYPE = 1
#次卡
UYU_STORE_PREPAY_TYPE = 0



#购买次数分润
UYU_BUYER_TYPE_PROFIT_SHARE = 0
UYU_BUYER_TYPE_MAP = {
    UYU_BUYER_TYPE_PROFIT_SHARE: '购买次数分润',
}

#套餐规则
#启用
UYU_RULES_STATUS_OPEN = 0
#关闭
UYU_RULES_STATUS_CLOSE = 1
UYU_RULES_STATUS_MAP = {
    UYU_RULES_STATUS_OPEN: '启用',
    UYU_RULES_STATUS_CLOSE: '关闭',
}

# 内部接口注册消费者同时赠送的次数
UYU_FREE_TRAINING_TIMES = 3


# 容联云短信参数
RONG_YUN_SMS_ACCOUNT_SID = '8a48b5514da42dc3014dade2c15e05ff'
RONG_YUN_SMS_ACCOUNT_TOKEN = '92c82d8cfd9949109fc8ed9e9d7785f4'
RONG_YUN_SMS_APPID = 'aaf98f894daddae8014dade49cba002c'
RONG_YUN_SMS_SERVER_IP = 'app.cloopen.com'
RONG_YUN_SMS_SERVER_PORT = '8883'
RONG_YUN_SMS_SOFT_VERSION = '2013-12-26'

RONG_YUN_SMS_UYU_TEMPID_VERIFY_CODE = 23073


# 渠道套餐绑定
# 绑定
UYU_CHAN_RULE_BIND = 1
# 解绑
UYU_CHAN_RULE_UNBIND = 0

# 项目和处方绑定关系
# 正常
UYU_PRESC_ITEM_BIND = 0
# 删除
UYU_PRESC_ITEM_UNBIND = 1

# 训练状态
# 开始训练
UYU_TRAIN_STATE_START = 1
# 结束训练
UYU_TRAIN_STATE_END = 2
# 训练关闭
UYU_TRAIN_STATE_CLOSE = 3
# 项目类型
# 检查项目
UYU_ITEM_CHECK = 1
# 训练项目
UYU_ITEM_TRAIN = 2
# 项目操作类型
UYU_ITEM_TYPE_CHECK = 1
UYU_ITEM_TYPE_TRAIN = 2
